// Generated by LiveScript 1.2.0
(function(){
  var triBaseLength, triRatio, triBaseHeight, out$ = typeof exports != 'undefined' && exports || this;
  triBaseLength = 32.0;
  triRatio = 1 / 1.61;
  triBaseHeight = triBaseLength * triRatio;
  out$.triBaseLength = triBaseLength;
}).call(this);
